version: "3"
services:
  php:
    image: babibubebon/lodfe:latest-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/lodfe

  nginx:
    image: babibubebon/lodfe:latest-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/lodfe
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
